config/routes.rb
::Rails.application.routes.draw do

#  devise_for :users,  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  match 'api' => 'api#api'

  scope :module => 'yuzublog' do
    resources :blogs do
      member do
        get 'rsd'
        get 'wlwmanifest'
      end
    end
    resources :posts, :shallow=>true do
      resources :comments
    end
  end

  # If the domain looks like www.*, it's considered a "network" domain
  #constraints(NetworkDomainConstraint) do
  #  root :to => 'blogs#index' 
  #end

  match 'about', :to => 'home#about'
  match 'contact', :to => 'home#contact'

  # home#index will figure out if there's a blog associated with the hostname, and redirect to blogs#index if
  # it can't find an association.
 # root :to => 'home#index'
end

app/controllers/home_controller.rb
  class HomeController < ApplicationController
    before_filter :find_blog
    
    public
    def index
      @posts=@blog.posts.recent.paginate(:per_page => 10,:page => params[:page])
    end

    def about
    end

    def contact
    end

  end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>BlogHome#about</h1>
<p>Find me in app/views/blog_home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>BlogHome#contact</h1>
<p>Find me in app/views/blog_home/contact.html.erb</p>

app/views/home/index.html.erb
<%title "#{@blog.name} : #{@blog.slug}" %>
<%content_for :blog_head do %>
  <link rel="EditURI" type="application/rsd+xml" title="RSD" href="<%=rsd_blog_url @blog, :format=>'xml' %>" />
<%end%>

<div class="posts recent">
  <h1>Recent Posts</h1>
  <%@posts.take(10).each do |post| %>

  <h2><%=link_to post.title, post%></h2>
  <div class="story">
    <%=post.story.html_safe%>
  </div>
  <%end%>
  
  <div class="pagination">
    <%=will_paginate @posts%>
  </div>
</div>

<div class="tags">
  <h1 class="tags">Tags</h1>
  <%tag_cloud(@tags,%w(tags1 tags2 tags3 tags4 tags tags5)) do |tag, css_class| 
# tag.name, { action => :tag, :id => tag.name}*/
%>
    <%=link_to tag.name,'',:class=> css_class %>
    <% end%>
</div>